### ISSUE TITLE
Documentation needs to be more clear

### ISSUE THREAD

**Issue by shubhamcodez** [rushabh-v/Show-Your-Contributions#2]
Instructions in the ReadMe are not clear and at times, confusing.

**Comment by shubhamcodez** [comment]
Probably, because I'm using Windows.

**Comment by rushabh-v** [comment]
Hey @shubhamcodez, Thanks for reporting that!
Where did you find in confusing? I think I can help you out!

**Comment by shubhamcodez** [comment]
I created a Personal Access Token but, what is a secret ? 
then, I went to Actions and there is no option to add a new Workflow.

Some problems I think were coz of different OS:
What does cp -r do and what to do after fetching and generating_doc.py

**Comment by rushabh-v** [comment]
Go to the `repo settings -> secrets -> new secret`. You will find `repo settings` on the first page of your repo, right after `insights`. Add your access token as a secret with the name `GIT_TOKEN`. We need to use it as a secret because we can not make our access token publically available. Others can misuse it.

I don't think there should be any problem with OS. `cp -r` will copy things recursively.

**Comment by shubhamcodez** [comment]
ok got it. Thanks a lot
